package com.lando.systems.June15GAM.tilemap;

/**
 * Brian Ploeckelman created on 5/12/2015.
 */
public enum TileTexture {

    BLANK,
    GROUND_CLAY,
    GROUND_CONCRETE,
    GROUND_GRASS,
    GROUND_ROAD,
    GROUND_SAND,
    GROUND_WATER,
    ROAD_CORNER_CURVE_NE,
    ROAD_CORNER_CURVE_SE,
    ROAD_CORNER_CURVE_NW,
    ROAD_CORNER_CURVE_SW,
    ROAD_CORNER_SQUARE_NE,
    ROAD_CORNER_SQUARE_SE,
    ROAD_CORNER_SQUARE_NW,
    ROAD_CORNER_SQUARE_SW,
    ROAD_FOURWAY,
    ROAD_LINE_THICK_N,
    ROAD_LINE_THICK_E,
    ROAD_LINE_THICK_S,
    ROAD_LINE_THICK_W,
    ROAD_LINE_THIN_END_N,
    ROAD_LINE_THIN_END_E,
    ROAD_LINE_THIN_END_S,
    ROAD_LINE_THIN_END_W,
    ROAD_LINE_THIN_H,
    ROAD_LINE_THIN_V,
    ROAD_TEE_THICK_N,
    ROAD_TEE_THICK_E,
    ROAD_TEE_THICK_S,
    ROAD_TEE_THICK_W,
    ROAD_TEE_THIN_N,
    ROAD_TEE_THIN_E,
    ROAD_TEE_THIN_S,
    ROAD_TEE_THIN_W

}
